In [2]:
import numpy as np


A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A + B:")
print(A + B)


print("A - B:")
print(A - B)


print("A * B:")
print(A * B)


A + B:
[[ 6  8]
 [10 12]]
A - B:
[[-4 -4]
 [-4 -4]]
A * B:
[[ 5 12]
 [21 32]]


## Basic Operations with Matrices
In this notebook, we will work on basic operations of matrices such as addition, subtraction, multiplication and division.
