## Inversion of a Matrix using Gauss-Jordan Elimination
This notebook explores how to find the inverse of a matrix using the Gauss-Jordan elimination method.

### Topics Covered:
1. Definition of matrix inverse
2. Gauss-Jordan elimination method
3. Step-by-step implementation


In [90]:
import numpy as np


matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]], float)


def gauss_jordan_inversion(matrix):
    augmented_matrix = np.hstack([matrix, np.eye(matrix.shape[0])])
    rows, cols = augmented_matrix.shape
    for i in range(rows):
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]
        for j in range(rows):
            if i != j:
                augmented_matrix[j] -= augmented_matrix[j, i] * augmented_matrix[i]
    return augmented_matrix[:, cols//2:]

inverse_matrix = gauss_jordan_inversion(matrix)
print("Inverse of the matrix is:")
print(inverse_matrix)


Inverse of the matrix is:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
