## Matrix Inversion Using Formula
In this notebook, we will explore how to compute the inverse of 2x2 matrices using the formula:

If `A = [[a, b], [c, d]]`, the inverse of `A` is:

`A⁻¹ = (1 / det(A)) * [[d, -b], [-c, a]]`

We will also verify the results using NumPy.



In [3]:
import numpy as np

# 2x2 Matrisin Tersi (Formülle)
matrix_2x2 = np.array([[4, 7], [2, 6]])
det = np.linalg.det(matrix_2x2)

if det != 0:
    inverse_manual = (1 / det) * np.array([[matrix_2x2[1, 1], -matrix_2x2[0, 1]],
                                           [-matrix_2x2[1, 0], matrix_2x2[0, 0]]])
    print("Matrix:")
    print(matrix_2x2)
    print("\nInverse (manual calculation):")
    print(inverse_manual)

    # NumPy ile Doğrulama
    inverse_numpy = np.linalg.inv(matrix_2x2)
    print("\nInverse (NumPy):")
    print(inverse_numpy)
else:
    print("Matrix is singular and cannot be inverted.")


Matrix:
[[4 7]
 [2 6]]

Inverse (manual calculation):
[[ 0.6 -0.7]
 [-0.2  0.4]]

Inverse (NumPy):
[[ 0.6 -0.7]
 [-0.2  0.4]]
